services:
  pg:
    image: "postgres:15.2-alpine"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
  rust:
    build: .
    develop:
      watch:
        - path: ./src
          action: rebuild
        - path: ./templates
          action: rebuild
    environment:
      DATABASE_URL: ${DATABASE_URL}
      OMDB_KEY: ${OMDB_KEY}
    ports:
      - 8080:8080
    depends_on:
      - pg
volumes:
  postgres:
